### ISSUE TITLE
Venus issues with raspi 3B+ with ver >2.70 to 2.80.14

### ISSUE THREAD

**Issue by RobDuthie** [kwindrem/SetupHelper#1]
Re canbus for raspi3B+ issues with not TX data, RX is OK in candump: Devices not showing up device list page.
USBcan and PiCan  via the SPI port
Being tested on:
PiCan Hat
CANable CANtact (both slcand and candelight firmware)
Testing on ver 2.73 , 2.80.14
With ver 2.66 all works OK.

**Comment by RobDuthie** [comment]
For raspi3B+ with 7inch touch screen.
To make the 6x relays active, needs these files. installed.
1: gpio_list
2: PageMain.qml
3: PageSettingsRelay.qml
4: PageSwitching.qml

**Comment by RobDuthie** [comment]
Raspi 3B+ VE direct ports issues with serial expansion HAT. VE Direct USB all OK
Not working on these versions of venus:
Testing on ver 2.73 , 2.80.14

**Comment by kwindrem** [comment]
These issues are not related to SetupHelper.

The relay issue is really part of RpiGpioSetup

The VE direct issues are not at all related to any of my packages

The CANbus issues are really part of VeCanSetup if they are issues.

**Comment by RobDuthie** [comment]
> These issues are not related to SetupHelper. Works fine
> 
> The relay issue is really part of RpiGpioSetup Works OK
> 
> The VE direct issues are not at all related to any of my packages Still needs testing for the serial porting
> 
> The CANbus issues are really part of VeCanSetup if they are issues. ? can't Tx data RX OK for USB or pican.
Hi Kevin
Not meant to be issues with your software (sorry for that) your software work very well, impressed. These are reports of what i have found with testing the new release with a raspi 3B+ after version 2.66.
Note: with your software you can now have 6x relay outputs showing on the device page.
If you want to work on this together to get the rest going will make this a full feature device for everybody. I have all the hardware in place i have a Cerbo, Multiplus2, MPPT, smart shunts, raspi 3 and 4 (4 ver1.4 PCB still not working on boot so can't test your software yet. Please advise.
Regards
Rob D
NZ

**Comment by RobDuthie** [comment]
Hi Kevin
Re canbus PiCan file to make it more stable i added the spi Frequency command below: Can you update your VeCanSetup file.
I had issues with data comming in the number were all over the place, by adding in the spi frequency the numbers are rock solid now.

#### begin CAN overlay DEV
# PiCAN Hat
# replace DEV with e.g., can0
[all]
dtparam=spi=on
dtoverlay=mcp2515-DEV-overlay,oscillator=16000000,interrupt=25,spimaxfrequency=500000
dtoverlay=spi-bcm2835-overlay
#### end CAN overlay

**Comment by kwindrem** [comment]
Done

**Comment by RobDuthie** [comment]
Cheers, That made all the difference to stable readings to BMS connected batteries on Canbus.
Running on Ver2.80.17 venus with your VeCanSetup all Ok no issues to date.
Re the raspi relay control and analog inputs, i have done a simple control code change in the PageSettingsRelay.qml page this acivate  4x more relay outputs without any other code change required. Changed .qml to PDF to upload here.
So just a matter of getting these to there own page now?
I have also the analog page working now with the 2 temps and 3 tanks all showing correct data on screen and 
VE Direct USB working OK
VE Direct I2C port still working on that one with configuration etc. It was OK on Ver <2.66.
Canbus USB OK
Canbus SPI port OK
Everything else is OK and working



.
[PageSettingsRelay.qml.pdf](https://github.com/kwindrem/SetupHelper/files/7180929/PageSettingsRelay.qml.pdf)

**Comment by kwindrem** [comment]
Couldn't open your PageSettingsRelay.qml file. Last time I looked, the necessary changes were pretty obvious.

Please continue discussions about CANbus in the VeCanSetup repo and about GPIOs in the RpiGpioSetup repo to keep things together. Posting here might cause me to miss something important.
