### ISSUE TITLE
Touchscreen calibration on 1024x600 px display (MPI7006)

### ISSUE THREAD

**Issue by rholze** [kwindrem/SetupHelper#103]
Hello, I am having problems setting my 7” display (MPI7006) and the touchscreen together correctly. I have configured the HDMI driver on the console with /data/Rpi/DisplaySetup/setup. Display and touchscreen worked fine together. But of course the correct resolution of 1024x600 pixels was not set. I therefore inserted the lines from the display manual into config.txt (http://www.lcdwiki.com/7inch_HDMI_Display-H)! Then a reboot and the resolution was correct. But now the touchscreen reacted, but you could no longer get into the MENU. Apparently something had been moved here. So I went back to the configuration and “only” called up the touchscreen calibration. But now the resolution was deleted from the config.txt again. How can I set the touchscreen resolution to 1024x600?
Thanks Ronald
default config ->
![IMG_20241118_103824_2](https://github.com/user-attachments/assets/79035492-5bb3-46ae-8f6a-88eb2f32ccf4)
config after editing the config.txt to a resolution to 1024x600
![IMG_20241118_103407_6](https://github.com/user-attachments/assets/9151fb6e-efc0-47d4-89f7-0769c94692b1)
configuration via script
![IMG_20241118_103609_0](https://github.com/user-attachments/assets/b3822380-d865-4be2-90d9-d909f9fb9f48)
my display
![IMG_20241118_103446_1](https://github.com/user-attachments/assets/2819b650-44a7-42f7-9d0d-7b17493c009f)

**Comment by kwindrem** [comment]
It appears RpiDisplaySetup script is modifying config.txt even when you run the touchscreen calibration only. This is what is undoing your manual changes. I need to fix this but in the mean time, I think you can specify your unit's configuration with a custom display configuration:

at the Select the HDMI mode from the above list (A / P / C): prompt, enter C

then specify 1024 for horizontal resolution, 600 for vertical resolution, 60 for refresh rate and 6 (15:9) for aspect

This should create the hdmi_cvt line per your unit's documentation.

After doing this, you will need to run touch screen calibration which will require a couple of reboots.

**Comment by kwindrem** [comment]
I updated the script to allow for running the touchscreen calibration without stepping on config.txt.

Still, I recommend using the custom option to enter your configuration. It is then remembered and will be available in the future if for some reason config.txt gets changed. Firmware updates won't generally touch config.txt but still ...
