### ISSUE TITLE
New PackageManager & blank Active Package

### ISSUE THREAD

**Issue by abucas01** [kwindrem/SetupHelper#11]
Hi Kevin,

/data/log/PackageManager folder  attached as requested

[LogDirPackageManager.zip](https://github.com/kwindrem/SetupHelper/files/7893762/LogDirPackageManager.zip)

I have run the following as suggested
svc -d /service/PackageManager
/data/SetupHelper/removeManagerSettings
svc -u /service/PackageManager

And this has removed the Blank Active Package entry

Thanks

**Comment by kwindrem** [comment]
Thanks for the logs. I did find something that happens during initialization. I'll put up a new version as soon as I've had some time to test it.

**Comment by kwindrem** [comment]
I think v4.2 fixes this
