### ISSUE TITLE
After the latest change, my 2 RPI running 2.85 are stuck on a constant GUI reboot.  I SSH and uninstalled setuphelper and the issue went away

### ISSUE THREAD

**Issue by pedrorampolla** [kwindrem/SetupHelper#16]

**Comment by pedrorampolla** [comment]
New load of 2.85 and either on blind install or via script, the problem starts as soon as setuphelper is installed and goes away as soon as it is removed.

**Comment by RobDuthie** [comment]
Yes it crashes gui mods have to reload new image to start again can't access as it loops and restarts.

**Comment by kwindrem** [comment]
Working fine here. Can someone send me gui, SetupHelper and PackageManger log files.

**Comment by kwindrem** [comment]
Should be fixed now in v5.23. If you have auto downloads and installs enabled, the problem will correct itself.

**Comment by RobDuthie** [comment]
Permission denied? whne reinstall setup helper?

**Comment by RobDuthie** [comment]
Still doing it missing ver file sets 2.85

**Comment by kwindrem** [comment]
Rob, are you still having issues with GuiMods v5.23? I deployed that last night. Works here on v2.85 firmware.
—
Kevin
