### ISSUE TITLE
123SmartBMS-Venus appearing on Active Packages whitout verion N.

### ISSUE THREAD

**Issue by GianFabris** [kwindrem/SetupHelper#19]
Hello, 
My set-up is:

- Multiplus II GX 48V 5000VA

- LiFePo4 200 Ah 48V battery pack

- 123 smart BMS

1. I have updated the Multiplus firmware to the latest version 497
2. I have updated the firmware of the GX unit to v2.87
3. I downloaded venus-data.tgc and copied to USB memory memory stick
4. Boot the system with memory stick
5. Reboot the system from GUI
6. Removed the memory stick while rebooting

What is appearing on Package manager under "Active packages" is a line **123SmartBMS-Venus** without indication of any stored or installed version.
Is that correct?

From this point how should I detect if 123 BMS is working?

**Comment by GianFabris** [comment]
![Active packages](https://user-images.githubusercontent.com/109231757/178775567-f82d5a7e-5da1-46b7-b053-a7dcaaa93a5b.png)

**Comment by AlbertronicDev** [comment]
Hi,

Where did you download the venus-data.tar.gz? The latest version can be found here: https://123electric.eu/products/123smartbms-to-usb/

Please put it on a USB, reboot twice and check again. If none works, please let us know.

**Comment by GianFabris** [comment]
Hi,
Thank you for your reply.
I downloaded the venus-data.tar.gz from here https://github.com/kwindrem/SetupHelper
I will try download the file from your link and let you know.
Thank you for support.

Gianluca Fabris

**Comment by kwindrem** [comment]
https://github.com/kwindrem/SetupHelper does not include the 123SmartBMS package. So there was nothing to install besides SetupHelper itself.

The one line on the 123 site DOES have the BMS package in addition to SetupHelper so that's the one you want.

With SetupHelper installed and your GX device connected to the internet, you could also use PackageManager (menus at the bottom of the Settings menu) to download the 123SmartBMS package. But I think the blind install provided by 123electric (not the one in SetupHelper) is fewer steps.

**Comment by GianFabris** [comment]
![Immagine%202022-07-14%20185212](https://user-images.githubusercontent.com/109231757/179052084-80207c09-ef76-46a3-98f8-ad6f82624d29.png)

![Immagine%202022-07-14%20185019](https://user-images.githubusercontent.com/109231757/179052116-fb07bc7b-d6c5-4c69-b459-356cf7a63cfa.png)

Hi,
Installing the venus-data.tar.gz provided by 123electric , i can see now the BMS parameters.
Can you coinfirm that the version 1.3 provide also control not only displayng?
Thank you foir your support

Gianluca

**Comment by AlbertronicDev** [comment]
Hi Gianluca,

v1.3 also can control the Victron system. Do not forget to enable DVCC and configure the Multiplus to listen to this. See "How to control a Victron with GX" at https://123electric.eu/products/123smartbms-gen3/

**Comment by GianFabris** [comment]
Thank you for the support
