### ISSUE TITLE
Won't load 2.90-22

### ISSUE THREAD

**Issue by MRRVRepair** [kwindrem/SetupHelper#20]
package manager and GUIMOD wont load in version 2.90-22

**Comment by kwindrem** [comment]
GuiMods v6.3 loads without issue here on Venus OS v2.90~22

SetupHelper (packageManager is part of SetupHelper) needed an update which is available now as v4.20. You will need to run the SetupHelper setup script manually sincePackage Manager is not running!. You can also revert to the previous version of Venus OS where PackageManager will still be running. Then wait for SetupHelper to update to v4.20. After that you can switch back to v2.90~22
