### ISSUE TITLE
Version 4.2 Backup & Restore

### ISSUE THREAD

**Issue by tlewis99** [kwindrem/SetupHelper#21]
Extremely minor issue with 4.2 backup and restore.  I'm running 2.90~22 which contains a new field under Settings/Display & language/Units/Tempature to select C [Celsius] or F [Fahrenheit.]  I make the change from the default of C to F , save and backup.  Upon restore to a factory default CerboGX with 2.90~22 the setting returns to the default of C.

Thanks for all your work,

Tim

**Comment by kwindrem** [comment]
Thanks for that. I'll add the new parameter to the list to be backed up.

**Comment by kwindrem** [comment]
done
