### ISSUE TITLE
SetupHelper removed with RC 2.90~24

### ISSUE THREAD

**Issue by drknight0** [kwindrem/SetupHelper#22]
tried to Install 2.90 ~24 tonight and after reboot both SuperHelper(4.21)/GuiTools(6.6) were removed

Reverting to ~22 restored access to both.

**Comment by kwindrem** [comment]
Sorry you are having issues.

The package reinstall should trigger a GUI restart but I just checked the logs on my Cerbo after the upgrade I just did on it and did not see a GUI restart. Looks like there might be a bug. Thanks.

A reboot should bring both packages up.

**Comment by kwindrem** [comment]
Fixed in SetupHelper v4.22
