### ISSUE TITLE
Guimods 7.4 don't work on Cerbo GX 

### ISSUE THREAD

**Issue by Zabrickx** [kwindrem/SetupHelper#33]
Installing is no problem, but after restarting the graphical interface is not OK. I took a screenshot.
![dont-work](https://user-images.githubusercontent.com/36524356/206178241-8eb88afa-83a4-4523-aa7a-38dc3c19a8b0.png)
Cerbo GX work with firmware version 2.92 large.
With RasPi everything works fine.
Thanks for the interesting tools for VenusOS.
regards
Jean Pierre

**Comment by kwindrem** [comment]
GuiMods v7.4 works fine on my Cerbo running v2.92 (normal and large).

**Comment by Zabrickx** [comment]
Hello Kwindrem, thanks for your quick reply. 
All my devices, such as the four solar charge controllers, are connected with ve-direct. 
Could that have something to do with this? 
Greatings 
Jean-Pierre 

Van: "kwindrem" ***@***.***> 
Aan: "kwindrem/SetupHelper" ***@***.***> 
Cc: "jean pierre krickx" ***@***.***>, "Author" ***@***.***> 
Verzonden: Woensdag 7 december 2022 17:53:38 
Onderwerp: Re: [kwindrem/SetupHelper] Guimods 7.4 don't work on Cerbo GX (Issue #33) 





GuiMods v7.4 works fine on my Cerbo running v2.92 (normal and large).

**Comment by Zabrickx** [comment]
Hello Kwindrem, after rebooting the Cerbo everything works fine. I thought I should just restart the gui. 
I'm glad everything works properly, I'm looking forward to additional options. Many thanks for this help. 
I wish you much success in all that you do. 
regards 
Jean Pierre 


Van: "kwindrem" ***@***.***> 
Aan: "kwindrem/SetupHelper" ***@***.***> 
Cc: "jean pierre krickx" ***@***.***>, "Author" ***@***.***> 
Verzonden: Woensdag 7 december 2022 17:53:38 
Onderwerp: Re: [kwindrem/SetupHelper] Guimods 7.4 don't work on Cerbo GX (Issue #33) 





GuiMods v7.4 works fine on my Cerbo running v2.92 (normal and large).

**Comment by kwindrem** [comment]
I have seen cases where devices did not appear after a Venus OS update. Nothing at all to do with GuiMods. Reboot always brings things back. Should have mentioned a reboot.
