### ISSUE TITLE
RpiDisplay from Command line

### ISSUE THREAD

**Issue by tompeel** [kwindrem/SetupHelper#34]
Hi All,

Os 2.92 large
RpiDisplaySetup 3.3

I get theessage to install this particulate package from the CMD line.

I can't see anything about this in the docs here or anything on Google?!

May not be a bug but If we can update the documentation that would be a help?

All other packages installing fine...

![Screenshot_20221219-195855](https://user-images.githubusercontent.com/6130043/208509971-7a402081-fc68-40ac-b9b2-aae1154c2e2a.png)
![Screenshot_20221219-195932](https://user-images.githubusercontent.com/6130043/208509992-d4e204c2-f294-494e-816a-7ba74e23e081.png)

**Comment by kwindrem** [comment]
Refer to the ReadMe for RpiDisplaySetup. It is already documented.
