### ISSUE TITLE
ExtTransferSwitch is missing from the package list

### ISSUE THREAD

**Issue by zorrobyte** [kwindrem/SetupHelper#37]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/7257172/210274373-5c0095bf-aed5-4f68-83fb-de983440d5ac.png">

<img width="516" alt="image" src="https://user-images.githubusercontent.com/7257172/210274355-4d5c167c-bad9-4f34-b241-33c7a38e1fd3.png">

ExtTransferSwitch's readme says to use SetupHelper for install and provides no manual packages for USB install. However, ExtTransferSwitch is not listed as installable.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/7257172/210274418-bfc929a1-1b4e-47a8-b860-09fda30b5cf3.png">

There is also an unpopulated "new" entry.

**Comment by kwindrem** [comment]
Use new to enter the information for this package:
name: ExtTransferSwitdh
GitHub user: kwindrem
GitHub branch: latest

It will then appear in the Active packages list. With auto downloads and installs active, it will eventually automatically install, or you can manually download and install from within the package from the Active packages list.

**Comment by zorrobyte** [comment]
The best, thanks!
