### ISSUE TITLE
Venus 3.00-20 Cant install package

### ISSUE THREAD

**Issue by peregrines2** [kwindrem/SetupHelper#42]
Hi!

Thank You for your great work!

Trying to install dbus-aggegregate-batteries by Dr-Gigavolt. Unfortunately i cant add it to Setuphelper.
Version stays empty and there is no option to download/install.

<img width="495" alt="Bildschirm­foto 2023-03-08 um 15 36 40" src="https://user-images.githubusercontent.com/9152610/223742018-a9a2a07d-bd23-4a3c-ac7e-e26aa8d1f366.png">
<img width="512" alt="Bildschirm­foto 2023-03-08 um 15 36 35" src="https://user-images.githubusercontent.com/9152610/223742024-73cd1024-4bec-45db-81e2-b5e91bc8af7f.png">

**Comment by kwindrem** [comment]
I looked at dbus-aggegregate-batteries and I don't see the files to indicate it has been set up to use Package Manager.

You will need to contact the package author to sort this out.
