### ISSUE TITLE
venus-data.tgz latest downloads v4.39 not v.4.40

### ISSUE THREAD

**Issue by tlewis99** [kwindrem/SetupHelper#49]
I download and install the latest venus-data.tgz file and under active packages it shows version 4.39 but version 4.40 available on GitHub.  Then I have to download and install 4.40 via the package manager.  Not sure if I'm doing something wrong?

Thanks,

Tim

**Comment by kwindrem** [comment]
Sorry, looks like I forgot to update the blind install archive when I did the v4.40 release. I'll fix it for the next release.

What you did is fine.
