### ISSUE TITLE
No original file in filesets

### ISSUE THREAD

**Issue by mr-manuel** [kwindrem/SetupHelper#52]
Hello Kevin,

I have a little problem since I'm not able to get it done correctly. How do I have to handle a new file `PageSettingsServicesNgrok.qml` that has different FileSets but no original?

I did not find this case in the documentation and now I spend a few hours to fix that somehow but without success.

Thanks for your help!

**Comment by kwindrem** [comment]
Unfortunately, the file set mechanism must have a stock file. So what I do in this case is create a file in the root of fileSets that points to another existing file in the Venus OS system that will likely contain differences between Venus OS versions when your file changes.

Another option is to place the file in the root of fileSets. The file then becomes version independent. This works if the file won't change from Venus OS version to version.
