### ISSUE TITLE
Unable to find correct fork/repo of Fronius package

### ISSUE THREAD

**Issue by pos-ei-don** [kwindrem/SetupHelper#83]
I have to file an issue for the fronius smartmeter package.
But i am unable to find the correct githilub link.
Can we have a list in the readme where we have to go when we need Support for a certain package?
Or am I just missing the correct lication where I can already find this Info?

**Comment by drtinaz** [comment]
If you click on the package in the package list, you will see the GitHub username and package name. You can then search for that user and package on GitHub.

https://github.com/SirUli/FroniusSmartmeter
