### ISSUE TITLE
Version 8 high data usage

### ISSUE THREAD

**Issue by lfhoward** [kwindrem/SetupHelper#89]
Hi Kevin,

Version 8 of SetupHelper just came out last night, which is awesome. Unfortunately my data usage went from approximately 0.5 MB per hour to about 5.5 MB per hour as soon as the new version was auto-installed. See the pic below of data usage from SixFab, my cellular carrier:

![IMG_0083](https://github.com/kwindrem/SetupHelper/assets/99151873/f1851aa3-50f4-4f90-b3f1-57b0d67169c1)

I have a mobile installation using a Raspberry Pi 4 as a cellular modem, which costs $9 a month if I keep data usage below 500 MB per month. Up to now that has worked. At the current data usage rate that is 11x higher, I am looking at $58-$87 per month for 4-6 GB of data... I would need to take my installation offline or come up with a different mobile internet solution. 

Would you be able to take a look at the data usage rate in version 8 of SetupHelper and see if you can bring it back to or close to pre-update levels?

Thanks for all you do for us in the Victron community! 
Sincerely,
Lauren

**Comment by kwindrem** [comment]
I will certainly look into this. It should not be happening. 

Until then, if you have not done so already, turn off automatic downloads.

**Comment by lfhoward** [comment]
Hi Kevin,Thanks a lot for taking a look at the code! I toggled Automatic GitHub Downloads to OFF for now. Best,LaurenOn May 16, 2024, at 1:13 PM, kwindrem ***@***.***> wrote:﻿
I will certainly look into this. It should not be happening.
Until then, if you have not done so already, turn off automatic downloads.

**Comment by kwindrem** [comment]
I found a bug that was requesting version information about every 10 seconds rather than every 10 minutes. This should make a significant difference. v8.1 is out now and will download with the branch/tag set to latest.

I am considering an enhancement to set the GitHub version refresh to once per day. But let me know if you think that's necessary after you log some data usage with 8.1 installed.

Thanks for reporting this. Most of us would not notice.

**Comment by lfhoward** [comment]
Kevin,Excellent. I’ll download 8.1 and let you know how it goes. Thank you for being so responsive. LaurenOn May 16, 2024, at 3:34 PM, kwindrem ***@***.***> wrote:﻿
I found a bug that was requesting version information about every 10 seconds rather than every 10 minutes. This should make a significant difference. v8.1 is out now and will download with the branch/tag set to latest.
I am considering an enhancement to set the GitHub version refresh to once per day. But let me know if you think that's necessary after you log some data usage with 8.1 installed.
Thanks for reporting this. Most of us would not notice.

**Comment by lfhoward** [comment]
Data usage is back to what it was before. I would be happy to have SetupHelper check once an hour or once every 6 hours. This would free up more data to be able to download OS updates and stay under my cap of 500 MB per month. 

![Uploading IMG_9284.png…]()

**Comment by kwindrem** [comment]
I just checked in SetupHelper v8.3 that adds GitHub check frequency: 10 minutes (the rate previously called Normal), Hourly and Daily. I'd be interested in how much this affects your network usage.

FYI, the version checks are spaced evenly across the specified time. For example, for every 10 minutes and 8 packages in the list that's one version check every 75 seconds. With 4 packages and Daily, that's one version check every 6 hours.

All GitHub versions are still refreshed quickly when entering the Active Packages menu. One package refresh occurs when navigating packages in the Package edit menu.

**Comment by lfhoward** [comment]
Following up on data usage:

Version 8.1 brought the data usage back in line to what it was before v. 8.0. Version 8.2 cranked the data rate back up to v. 8.0 levels. I just downloaded 8.3 and set the interval to “daily” so I’ll let you know what happens. The spike on the most recent hour is probably me downloading 8.3 on top of the high data usage from 8.2.

![IMG_0085](https://github.com/kwindrem/SetupHelper/assets/99151873/1b9c0b27-64fe-4a99-a7cd-d334f1843aa4)

**Comment by lfhoward** [comment]
Results of setting the refresh rate to daily:

![IMG_9297](https://github.com/kwindrem/SetupHelper/assets/99151873/cb461757-d6a2-43f6-8fa0-748c5aaa8cc0)

Minimal data usage!!! This makes me happy. It is even less than before, so that means I have more leeway to play around with the system, download updates, and not have to worry about hitting my monthly data cap. 

Thank you Kevin!

**Comment by lfhoward** [comment]
Data usage continues to be low and manageable.  This flexibility is a really good feature of the new version. 

![IMG_9324](https://github.com/kwindrem/SetupHelper/assets/99151873/a8453767-29e0-478d-9dfb-98e0e4fb6f16)

**Comment by kwindrem** [comment]
Glad it's working well for you.

Closing issue now
