### ISSUE TITLE
RS485

### ISSUE THREAD

**Issue by Cyberb29** [kwindrem/SetupHelper#91]
Do you perhaps have a dtbo overlay that will allow for the use of the onboard RS485 of the WaveShare RS485 CAN HAT (RS485 CAN HAT B) this one for example: https://www.waveshare.com/rs485-can-hat.htm ?

If you do could you add this to the setuphelper? I want to make use of this to connect a ET112 for example.

**Comment by kwindrem** [comment]
Sorry, I don't know enough about this board and how it works, nor how Venus OS could interface to it.
