### ISSUE TITLE
Package install -> install from command line

### ISSUE THREAD

**Issue by Tobi266** [kwindrem/SetupHelper#94]
![Screenshot_20240710-113800](https://github.com/kwindrem/SetupHelper/assets/84711635/c1cf64bf-5ec7-4d8e-b0c8-716335d62716)
Hi,
I'm struggling to install VeCanSetup.
Brand new installation with 3.34 large image on Raspberry Pi 3B.
Installed actual setup helper with tar.gz and USB stick.
Afterwards reboot.
Then installed shutdownMonitor and after that VeCanSetup.
But the installation of it failed or is not automated.
I always get the hint "install from command line"
Any suggestions? Or how to install package manual via command line?

Regards

**Comment by kwindrem** [comment]
You must have command line access to your GX device since configuration of VeCanSetup is not possible from the GUI screen. There are just too many options. The ReadMe file included in the VeCanSetup GitHub repo explains the configuration steps in detail.
